Fix rubocop violations
* Ignore foodcritic rule #009 for windows package success_codes
* Refactor winrm recipe's if statements to remove one nested block
* Fix `NoMethodError: undefined method `empty' for nil:NilClass`
when powershell.winrm.thumbprint is nil